version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: frontend-container
    volumes:
      - ./ramen_project:/app       
    working_dir: /app
    ports:
      - 8080:80
    tty: true
    networks:
      - app_network

networks:
  app_network:
    external: true
