apiVersion: v1
kind: Service
metadata:
  name: front
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-1:550833571986:certificate/c79b8c8d-f1ee-4150-9c96-832ef856dbdc
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    back: front
  ports:
  - name: https
    port: 443
    targetPort: 80
