apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: snd1231/front
    context: .
    docker:
      dockerfile: ./docker/Dockerfile
  local:
    push: true

deploy:
  kubectl:
    manifests:
      - front-deployment.yaml

